### ISSUE TITLE
Cannot parse destructuring in lambda arguments

### ISSUE THREAD

**Issue by MichalPokorny** [JukkaL/mypy#746] opened 2015-08-17 17:04 UTC
```
adder = lambda (x, y): x + y
```
=> `error: Parse error before (`

**Comment by o11c** [comment] 2015-08-17 17:10
I'm working on it, but probably will *only* support it for the parse step, not for analysis.

**Comment by JukkaL** [comment] 2015-08-23 22:59
This can also be used in regular function definitions (#785). This is a Python 2 only feature.

**Comment by gnprice** [comment] 2015-10-19 22:53
Merging information from a duplicate of this issue: in #934, @jhance proposed handling this by a desugaring, and @JukkaL and I both agreed that that's a good solution.

A v1 of that solution will probably mean confusing error messages if a desugared parameter ends up involved in an error, but we all felt that's an acceptable tradeoff because the construct is so rarely used.

**Comment by JukkaL** [comment] 2015-11-22 17:17
This works now.

**Closed by JukkaL** 2015-11-22 17:17 UTC
Labels: feature, priority
