### ISSUE TITLE
Awaitable support

### ISSUE THREAD

**Issue by ddfisher** [JukkaL/mypy#1139] opened 2016-01-18 07:57 UTC
[PEP 492](https://www.python.org/dev/peps/pep-0492/) adds `async def`, `await`, and `Awaitable` objects.  mypy doesn't support these yet, but should eventually.

**Comment by JukkaL** [comment] 2016-01-18 09:55
Duplicate of #706.

**Closed by JukkaL** 2016-01-18 09:55 UTC
Labels: duplicate, feature
