### ISSUE TITLE
Totality Checks

### ISSUE THREAD

**Issue by mvcisback** [JukkaL/mypy#388] opened 2014-08-16 07:55 UTC
In a lot of typed languages, the compiler can be told to check if a function is *total*, handles all cases.

For Example:
```python
def foo(x: Union[int, str]) -> str:
    if isinstance(x, int):
        return "bar"
```
Is only a partial function. If `x` is a `str`, then this function actually returns `None`.
Thus the output type should really be `Union[str, NoneType]`

I tested this snippet and mypy doesn't seem to catch this.
I'm not 100% sure, but I think if a function is partial, `NoneType` is a potential return type.

**Comment by gvanrossum** [comment] 2016-01-08 18:21
Let's call this a duplicate of #302.

**Closed by gvanrossum** 2016-01-08 18:21 UTC
Labels: bug
