### ISSUE TITLE
Parse failure on Python 2 tuple-params

### ISSUE THREAD

**Issue by gnprice** [JukkaL/mypy#934] opened 2015-10-15 19:10 UTC
Python 2 allows a limited form of pattern-matching in function parameters:
```
$ cat /tmp/foo.py
def f((a, b)):
  return a
print(f((1,2)))
$ python2 /tmp/foo.py
1
```

But mypy doesn't parse this, even in `--py2` mode:
```
$ mypy --py2 /tmp/foo.py
/tmp/foo.py: note: In function "f":
/tmp/foo.py:1: error: Parse error before (
/tmp/foo.py:1: error: Parse error before )
/tmp/foo.py: note: At top level:
/tmp/foo.py:1: error: Parse error before :
/tmp/foo.py:2: error: Inconsistent indentation
/tmp/foo.py:3: error: Inconsistent indentation
```

**Comment by kirbyfan64** [comment] 2015-10-15 19:36
I'm weird and miss this feature in Python 3. :(

**Comment by jhance** [comment] 2015-10-15 20:15
#929 should probably help a bit here as this would be a new 'kind' of argument I presume?

**Comment by gnprice** [comment] 2015-10-15 22:58
Yeah.

I think the use of this construct is quite rare -- from a quick scan of attempting to typecheck a random sample of Dropbox's code with mypy and looking for parse errors, I'm confident <0.5% of files do it. And the two examples I've found (in 1000 files) are both tiny lambdas, so type errors inside these functions which would cause us to spit out error messages potentially mentioning a desugared argument like `__mypy_tuple_1` will be even rarer.

So that sounds like a good solution to me. An optional bonus feature would be, if we do spit out an error in such a function (or better yet one actually mentioning the desugared argument), we add a note explaining that a tuple-param was desugared, so the strange name is less surprising.

**Comment by JukkaL** [comment] 2015-10-16 04:19
Ah yes, I've hit this myself a few times but forgot to create an issue.

I agree that desugaring is a good approach for dealing with this. I also like the idea of recognizing the desugared arguments when generating errors and doing something reasonable, but this is not essential for the first iteration.

Add 'priority' as I'd like to get the parser handle all of Python 2 (and 3) so that we can more easily run experiments against large code bases. The stub generator will also benefit from having a robust parser, and creating stubs is another priority.

**Comment by JukkaL** [comment] 2015-10-18 18:25
Closing as duplicate of #746 and #785.

**Closed by JukkaL** 2015-10-18 18:25 UTC
Labels: feature, priority
