### ISSUE TITLE
Broken yield parsing in python 2.7

### ISSUE THREAD

**Issue by kylec1** [JukkaL/mypy#751] opened 2015-08-17 18:21 UTC
Code:
  
     def wrapped(*args, **kwargs):
          with new_scope(g, r):
                ret = yield f(*args, **kwargs)

results in ` error: Parse error before "f"`.

**Comment by o11c** [comment] 2015-08-17 18:25
Duplicate of #498 which I am already working on.

**Comment by JukkaL** [comment] 2015-08-19 00:34
We are are currently blocked on this, so I'll implement a quick hack the lets mypy process code such as the example above, but doesn't actually do useful type checking.

**Closed** 2015-08-19 01:13 UTC
Labels: hack
