### ISSUE TITLE
Generic type alias?

### ISSUE THREAD

**Issue by desmond-dsouza** [JukkaL/mypy#1037] opened 2015-12-02 22:03 UTC
Not sure if this is `Question` or `Issue`. Is the `IterFunc` alias below allowed? There is no other way to alias a complex generic types. 
```
from typing import TypeVar, Callable, Iterator, Iterable

T = TypeVar("T")

IterFunc = Callable[[], Iterator[T]]

def s_map(f: Callable[[T], T], l: Iterable[T]) -> IterFunc:
    return lambda: map(f, l)
```

Mypy rejects it with:

```
 Invalid type "__main__.T"
```
Thanks.

**Comment by JukkaL** [comment] 2015-12-02 22:21
It's not supported yet, but I think that PEP 484 allows it. 

There is another possible interpretation of the alias that was discussed before (I can't find the issue), in which `X = Dict[str, T]` would make `X[int]` mean `Dict[str, int]`, for example.

**Comment by gvanrossum** [comment] 2015-12-03 05:17
Yes, PEP 484 explicitly allows this. I think the other issue you're thinking of is in typehinting: https://github.com/ambv/typehinting/issues/115. Also that mentions #606 here, which this is probably a duplicate of.

**Comment by JukkaL** [comment] 2015-12-03 07:31
Yeah, this looks like a duplicate of #606. Closing this.

**Closed by JukkaL** 2015-12-03 07:31 UTC
Labels: feature
