### ISSUE TITLE
"already defined" errors when adding type annotations in multiple code paths

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1191] opened 2016-01-29 06:18 UTC
While trying to debug something, I ended up adding type annotations for the definitions of an object in both code paths, and got a `/home/tabbott/foo.py:10: error: Name 'child_pid' already defined` with this (simplified) code:
```
if True:
    child_pid = os.fork() # type: int
    # Do stuff
else:
    child_pid = None # type: int
```
Since the types are the same, it seems like this shouldn't be an error.

This may be a variant of #1153.

**Comment by gvanrossum** [comment] 2016-01-29 17:44
Hm, I think mypy actually has an intentional rule that you shouldn't annotate a variable twice, and I like that rule. So I am tempted to reject this one. The right fix would be to make the first annotation `Optional[int]`.

**Comment by JukkaL** [comment] 2016-01-29 19:58
Yeah, this is by design.

**Comment by JukkaL** [comment] 2016-02-04 15:55
Closing this now. Feel free to reopen if you don't agree :-)

**Closed by JukkaL** 2016-02-04 15:55 UTC

**Comment by ruuda** [comment] 2018-07-11 12:39
Somewhat related, this error also triggers even when `del` is used:

```python
if True:  # For example, should not be const in practice.
    foo: int = 0
    print(foo)
    del foo
else:
    foo: int = 0
    print(foo)
```

In the following example it even reports an error: "Trying to read deleted variable 'foo'" on the last line.

```python
if True:  # For example, should not be const in practice.
    foo: int = 0
    print(foo)
    del foo

foo: int = 0
print(foo)
```

I am using Mypy 0.610.

**Comment by gvanrossum** [comment] 2018-07-11 15:00
There should be only one declaration of a given variable per scope. And a function is one scope.

**Comment by impredicative** [comment] 2019-01-14 19:12
> There should be only one declaration of a given variable per scope.

This recommendations seems wholly unreasonable. Python itself has no such restriction. I feel lousy having to change my variable names just to make mypy happy.

**Comment by gvanrossum** [comment] 2019-01-14 19:17
We are actively working on this restriction.

**Comment by JukkaL** [comment] 2019-01-15 16:41
The initial implementation will likely only cover redefinition within a single block at the same nesting level, but it's possible that we'll extend it to handle other cases in the future.

**Comment by komuw** [comment] 2019-03-09 13:05
> The initial implementation will likely only cover redefinition within a single block         

@JukkaL should this github issue be re-opened?

I just ran into this is in my code.

```python
import typing, logging

def convertLog(log_level: typing.Union[str, int]) -> int:
    """
    usage:
       level = convertLog(log_level="DEBUG") 
       assert level == 10
    """
    if isinstance(log_level, str):
        log_level: int = logging._nameToLevel[log_level.upper()]
    return log_level

```
`mypy` complains about `log_level already defined`.      
However, do note that a `log_level` enters the function either as an `int` or a `str` but can only come out as an `int`

**Comment by ilevkivskyi** [comment] 2019-03-11 18:11
@komuw You can simply remove that `: int` annotation, it is just not needed there.

**Comment by ngie-eign** [comment] 2019-09-24 21:26
I'm running into this as well with the following code:
```
try:
    from unittest import mock  # python 3
except ImportError:
    import mock  # python 2
```

**Comment by bela127** [comment] 2020-02-23 16:12
Same Problem in the flowing to implementations
Note that implementation 2 is the way of annotating for loops per pep

so it definitely should be supported to have for loops with different types for the running variable

```
class Functionality():
   
    def __init__(self: Functionality, func: Callable[Info,Any]):
        super().__init__()
        self.func: Callable[Info,Any] = func
        self.pre_call: List[PreExpert] = []
        self.post_call: List[PostExpert] = []
        
    def __call__(self: Functionality, info):
      
        for expert in self.pre_call:
            if expert.can_work_with(info):
                expert.execute(info)
        
        ret = self.func(info)

        for expert in self.post_call:                    ##Problem
            if expert.can_work_with(info):
                expert.execute(info)
                
        return ret
```
```
class Functionality():
   
    def __init__(self: Functionality, func: Callable[Info,Any]):
        super().__init__()
        self.func: Callable[Info,Any] = func
        self.pre_call: List[PreExpert] = []
        self.post_call: List[PostExpert] = []
        
    def __call__(self: Functionality, info):
        expert: PreExpert
        for expert in self.pre_call:
            if expert.can_work_with(info):
                expert.execute(info)
        
        ret = self.func(info)
        
        expert: PostExpert  ##Problem
        for expert in self.post_call:
            if expert.can_work_with(info):
                expert.execute(info)
                
        return ret
```

**Comment by JukkaL** [comment] 2020-02-28 18:03
You can try `--allow-redefinition` -- it will let you redefine some variables (though not always).

**Comment by DevilXD** [comment] 2020-03-03 10:20
I'm having an issue where this redefinition check ignores pathways that will never happen at runtime, for example where the code takes a path after an `if` check, that ends with a `return`. Simplified example:

```py
key: Union[int, str]

if isinstance(key, int):
    ...
    result: Tuple[int, str] = ...
    ...
    return result
...  # here the type of 'key' is 'str' only
result: Tuple[int, str] = ...  # here is the redefinition error, pointing at the line inside the if check above as the original definition
...
return result
```

**Comment by cipollone** [comment] 2021-02-17 10:48
I'm fine with the rune "only one annotation per scope". To me, the problem is just that the error is not informative enough. Both the error text and the [example](https://mypy.readthedocs.io/en/stable/error_code_list.html#check-that-each-name-is-defined-once-no-redef) in the documentation suggest that it may be a coding issue. Instead, I just had to remove the second annotation!
```python
if not resuming:
  # Initialize
  obj = MyClass()
else:
  # Load back
  obj: MyClass = loader.deserialize()
```
Without this github issue I couldn't figure out what was wrong.

**Comment by parhamfh** [comment] 2022-11-18 12:11
Stumbled upon this as well, perhaps if this is helpful to some but not to others it could be turned into [a warning](https://mypy.readthedocs.io/en/stable/command_line.html#configuring-warnings) instead. This feels like checking code style.

**Comment by bafulton** [comment] 2023-02-06 16:11
I just stumbled onto this now. I agree with @JulesGM and @parhamfh--this feels too prescriptive to me. I'd be in favor of making it a warning.
