### ISSUE TITLE
Crash in function_type()

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#998] opened 2015-11-24 21:25 UTC
The source has:
```
# Make the decorator available to all.
on_ui_thread = MainMessageQueue.on_queue
```
The crash log is:
```
Traceback (most recent call last):
  File "/Users/guido/src/mypy/scripts/mypy", line 6, in <module>
    main(__file__)
  File "/Users/guido/src/mypy/mypy/main.py", line 49, in main
    type_check_only(sources, bin_dir, options)
  File "/Users/guido/src/mypy/mypy/main.py", line 92, in type_check_only
    python_path=options.python_path)
  File "/Users/guido/src/mypy/mypy/build.py", line 197, in build
    result = manager.process(initial_states)
  File "/Users/guido/src/mypy/mypy/build.py", line 379, in process
    next.process()
  File "/Users/guido/src/mypy/mypy/build.py", line 849, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/Users/guido/src/mypy/mypy/checker.py", line 371, in visit_file
    self.accept(d)
  File "/Users/guido/src/mypy/mypy/checker.py", line 379, in accept
    typ = node.accept(self)
  File "/Users/guido/src/mypy/mypy/nodes.py", line 552, in accept
    return visitor.visit_assignment_stmt(self)
  File "/Users/guido/src/mypy/mypy/checker.py", line 953, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
  File "/Users/guido/src/mypy/mypy/checker.py", line 981, in check_assignment
    self.infer_variable_type(inferred, lvalue, self.accept(rvalue),
  File "/Users/guido/src/mypy/mypy/checker.py", line 379, in accept
    typ = node.accept(self)
  File "/Users/guido/src/mypy/mypy/nodes.py", line 929, in accept
    return visitor.visit_member_expr(self)
  File "/Users/guido/src/mypy/mypy/checker.py", line 1770, in visit_member_expr
    return self.expr_checker.visit_member_expr(e)
  File "/Users/guido/src/mypy/mypy/checkexpr.py", line 680, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "/Users/guido/src/mypy/mypy/checkexpr.py", line 693, in analyze_ordinary_member_access
    self.named_type, self.msg)
  File "/Users/guido/src/mypy/mypy/checkmember.py", line 84, in analyze_member_access
    result = analyze_class_attribute_access(itype, name, node, is_lvalue, builtin_type, msg)
  File "/Users/guido/src/mypy/mypy/checkmember.py", line 240, in analyze_class_attribute_access
    return function_type(cast(FuncBase, node.node), builtin_type('builtins.function'))
  File "/Users/guido/src/mypy/mypy/nodes.py", line 1733, in function_type
    if func.type:
AttributeError: 'Decorator' object has no attribute 'type'

*** INTERNAL ERROR ***

ui/common/uikit.py:64: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
```

**Comment by kirbyfan64** [comment] 2015-11-24 21:43
@gvanrossum If in `mypy/checkmember.py`, you put the following right after line 230:

```python
print(node, t)
```

what is the output?

**Comment by gvanrossum** [comment] 2015-11-24 22:02
The last two lines of that output say:
```
Mdef/Decorator : def (cls: Any, html: Any) -> Any def (cls: Any, html: Any) -> Any
Mdef/Decorator : def () -> Any def () -> Any
```
(I have not been able to reproduce the issue in a smaller setting -- the offending line is a class method that implements the tedious pattern to support both `@foo` and `@foo()`, and the actual decorator is an invocation of something else. The code base I am trying this on is huge and I am not very familiar with it yet, so navigating it is slow.)

**Comment by kirbyfan64** [comment] 2015-11-24 22:45
@gvanrossum ...what if you change it to read:

```python
print(node, t, node.node)
```

I think I'm getting an idea of what the issue is.

**Comment by JukkaL** [comment] 2015-11-24 23:04
I have a repro, I think:

```
A.g()

class A:
    @f
    def g(self): pass


def f(x):
    return x
```

**Comment by JukkaL** [comment] 2015-11-24 23:08
I landed a workaround. Let me know if this fixes the crash.

**Comment by gvanrossum** [comment] 2015-11-25 00:10
Now I get a different error (on the same file):
```
Traceback (most recent call last):
  File "/Users/guido/src/mypy/scripts/mypy", line 6, in <module>
    main(__file__)
  File "/Users/guido/src/mypy/mypy/main.py", line 49, in main
    type_check_only(sources, bin_dir, options)
  File "/Users/guido/src/mypy/mypy/main.py", line 92, in type_check_only
    python_path=options.python_path)
  File "/Users/guido/src/mypy/mypy/build.py", line 197, in build
    result = manager.process(initial_states)
  File "/Users/guido/src/mypy/mypy/build.py", line 379, in process
    next.process()
  File "/Users/guido/src/mypy/mypy/build.py", line 849, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/Users/guido/src/mypy/mypy/checker.py", line 371, in visit_file
    self.accept(d)
  File "/Users/guido/src/mypy/mypy/checker.py", line 379, in accept
    typ = node.accept(self)
  File "/Users/guido/src/mypy/mypy/nodes.py", line 473, in accept
    return visitor.visit_class_def(self)
  File "/Users/guido/src/mypy/mypy/checker.py", line 871, in visit_class_def
    self.check_multiple_inheritance(typ)
  File "/Users/guido/src/mypy/mypy/checker.py", line 889, in check_multiple_inheritance
    self.check_compatibility(name, base, base2, typ)
  File "/Users/guido/src/mypy/mypy/checker.py", line 925, in check_compatibility
    ok = is_equivalent(first_type, second_type)
  File "/Users/guido/src/mypy/mypy/subtypes.py", line 60, in is_equivalent
    return is_subtype(a, b, type_parameter_checker) and is_subtype(b, a, type_parameter_checker)
  File "/Users/guido/src/mypy/mypy/subtypes.py", line 49, in is_subtype
    return left.accept(SubtypeVisitor(right, type_parameter_checker))
AttributeError: 'NoneType' object has no attribute 'accept'

*** INTERNAL ERROR ***

ui/common/uikit.py:366: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
```

**Comment by JukkaL** [comment] 2015-11-25 06:10
I just pushed an attempt at fixing this issue. This is probably related to #613, which is probably one of worst known issues right now.

**Comment by gvanrossum** [comment] 2015-11-25 18:57
Thanks, the crash is gone.

**Closed** 2015-11-26 21:01 UTC
Labels: bug, priority
