### ISSUE TITLE
Errors when using defaultdict

### ISSUE THREAD

**Issue by rowillia** [JukkaL/mypy#995] opened 2015-11-24 08:26 UTC
defaultdict's documentation suggests passing `list` as an argument to defaultdict - https://docs.python.org/2/library/collections.html#defaultdict-examples

mypy complains when I do this however

```py
from collections import defaultdict

foo = defaultdict(list)
bar = defaultdict(dict)
```

Results in:

```
default_dict_example.py, line 3: Argument 1 to "defaultdict" has incompatible type List[_T]; expected Callable[[], List[_T]]
default_dict_example.py, line 3: Need type annotation for variable
default_dict_example.py, line 4: Argument 1 to "defaultdict" has incompatible type Dict[_KT, _VT]; expected Callable[[], Dict[_KT, _VT]]
default_dict_example.py, line 4: Need type annotation for variable
```

**Comment by gvanrossum** [comment] 2015-11-24 18:33
This seems a symptom of a general problem where classes don't seen to be considered compatible with callables. I've found a few other instances of this too.

**Comment by rowillia** [comment] 2015-11-25 00:16
Changing this to `defaultdict(lambda: dict())` can be used as a work around, but then items coming out of the `defaultdict` aren't being type checked - 

```
bar = defaultdict(lambda: dict())
bar.foobar() # works
bar['0'].foobar() # also works
```

**Comment by rowillia** [comment] 2015-11-25 00:25
Hmm, weird.  In a standalone file I get an error about bar needing a type (which is equally strange).  In the real example it's ignoring it's type.

**Comment by gvanrossum** [comment] 2015-11-25 00:56
Hm, this works for me:
```
bar = defaultdict(dict)  # type: MutableMapping[Any, Dict]
```

**Comment by JukkaL** [comment] 2015-11-25 05:58
Ah this is a dupe of #815.

**Closed by JukkaL** 2015-11-25 05:58 UTC
Labels: bug, duplicate, priority
