### ISSUE TITLE
A possible syntax for a function type with a varargs argument list

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#540] opened 2014-12-20 05:42 UTC
I just skimmed the README for Reticulated Python (https://github.com/mvitousek/reticulated). They have a useful hack to spell the type of a function with varargs or other dynamic hacks in the argument list: a normal function type is spelled e.g. Function([Int, Int], Float); a function type with a varargs argument list is spelled e.g. Function(DynParameters, Float). In mypy this would be Function[DynParameters, float]. (Or pick some other name for DynParameters.)

**Comment by gvanrossum** [comment] 2015-01-05 21:05
Hm... The use cases for your Args typevar seem meager, and the TL looks confusingly like a function of one arg. (Especially ``Tuple[TL]`` seems wrong, it appears to be a 1-tuple whose item is a TL.) I'd like to have something simpler, a single predefined name that just means "callable with any arguments at all. including keyword args." Reusing Any or None for this feels like it would easily be confused (I'm thinking here of someone seeing ``Callable[Any, int]`` and thinking it means ``Callable[[Any], int]``).

Instead, let's have a predefined name AnyArgs that can be used instead of a list of argument types, e.g. ``Callable[AnyArgs, int]`` is a function with an unconstrained argument list returning an int. AnyArgs would just be a marker object that doesn't have any behavior (it wouldn't be considered a type or class, and would be illegal everywhere else).

**Comment by ambv** [comment] 2015-01-07 06:41
Was the use of ellipsis considered?

```Callable[..., int]```

**Comment by gvanrossum** [comment] 2015-01-07 19:02
Ah, I actually like Callable[..., int]. I can't recall if it was considered before or not (I think we only rejected None and Any, because both are valid types (None being a shortcut for NoneType) and Callable[Any, int] looks like a typo for Callable[[Any], int].

Jukka, what do you think? Does Callable[..., int] work for mypy?

**Comment by JukkaL** [comment] 2015-01-08 05:05
Cool, I didn't remember that :-)

**Comment by JukkaL** [comment] 2015-05-17 17:43
Closing as this is a dupe of #393.

**Closed by JukkaL** 2015-05-17 17:43 UTC
Labels: enhancement proposal
